notifications:
  email:
    on_success: never
    on_failure: always

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - php -S localhost:8000 -t ./tests/public > /dev/null 2>&1 &

script: phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
